"""Initial migration

Revision ID: 5168f64bad08
Revises: 
Create Date: 2025-09-08 15:55:14.518682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5168f64bad08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###